#!/bin/sh
############################################################################

picom &

nitrogen --restore &

~/.config/polybar/scripts/launch-polybar &

libinput-gestures-setup start &

dunst &

batsignal -b &

flameshot &

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# [!!!] IMPORTANT FOR JetBrains APPS
# see https://github.com/baskerville/bspwm/issues/52
wmname LG3D

############################################################################
