#!/bin/sh
############################################################################

picom &

redshift -l "55.984768:92.755751" &

nitrogen --restore &

~/.config/polybar/scripts/launch-polybar &

libinput-gestures-setup start &

dunst &

batsignal -b &

flameshot &

bolt --generate

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# [!!!] IMPORTANT FOR JetBrains APPS
# see https://github.com/baskerville/bspwm/issues/52
wmname LG3D

############################################################################
