#! /bin/zsh
############################################################################
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#  Edited by Shishqa 
#
############################################################################

export BSPWM_CONFIG="$HOME/.config/bspwm"

############################################################################

bspc config window_gap              10
bspc config corner-radius           8

bspc config border_width            1
bspc config normal_border_color     "#121212"
bspc config focused_border_color    "#DEDEDE"

bspc config split_ratio             0.6180
bspc config automatic_scheme        longest_side
bspc config removal_adjustment      true
bspc config auto_cancel             true
bspc config initial_polarity        second_child

bspc config gapless_monocle         false
bspc config borderless_monocle      true
bspc config single_monocle          true

bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config focus_by_distance       true

############################################################################

if [[ $(xrandr --query | grep 'DP1 connected')
 ]]; then
    bspc monitor DP1 -d 1 2 3 4  
    bspc monitor eDP1 -d 5 6 7 8
else
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8
fi

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
bspc rule --add Pick-colour-picker        state=floating sticky=on
bspc rule --add vlc                       state=floating 
bspc rule --add feh                       state=floating 
bspc rule --add URxvt:calendar            state=floating
bspc rule --add URxvt:htop                state=floating
bspc rule --add URxvt:ncmpcpp             state=floating
bspc rule --add URxvt:update              state=floating
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#


sxhkd &
"$BSPWM_CONFIG/autostart" &


############################################################################
#
#  ███████╗ ██████╗ ███████╗
#  ██╔════╝██╔═══██╗██╔════╝
#  █████╗  ██║   ██║█████╗
#  ██╔══╝  ██║   ██║██╔══╝
#  ███████╗╚██████╔╝██║
#  ╚══════╝ ╚═════╝ ╚═╝
#
############################################################################
