#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

CONFIG=$HOME/.config/polybar/bars.ini

polybar --config=$CONFIG top &
polybar --config=$CONFIG bottom &

if [[ $(xrandr -q | grep 'DP1 connected') ]]; then
    polybar --config=$CONFIG top_external &
    polybar --config=$CONFIG bottom_external &
fi

